import "../../styles/transactionDetailsDrawer.css";
import jsPDF from "jspdf";
import { toast } from "react-toastify";
function TransactionDetailsDrawer({
  transaction,
  open,
  onClose
}) {

  if (!open || !transaction) {
    return null;
  }

  const formatDate = (date) => {

    if (!date) return "-";

    return new Date(date).toLocaleDateString(
      "en-IN",
      {
        day: "2-digit",
        month: "short",
        year: "numeric"
      }
    );

  };

  const formatTime = (date) => {

    if (!date) return "-";

    return new Date(date).toLocaleTimeString(
      "en-IN",
      {
        hour: "2-digit",
        minute: "2-digit"
      }
    );

  };
const downloadReceipt = () => {

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("NeuroWallet", 20, 20);

    doc.setFontSize(16);
    doc.text("Transaction Receipt", 20, 35);

    doc.line(20, 40, 190, 40);

    doc.setFontSize(12);

    doc.text(
        `Reference : TXN-${transaction.transactionId}`,
        20,
        55
    );

    doc.text(
        `Amount : ₹${transaction.amount}`,
        20,
        65
    );

    doc.text(
        `Status : ${transaction.status}`,
        20,
        75
    );

    doc.text(
        `Type : ${transaction.type}`,
        20,
        85
    );

    doc.text(
        `Category : ${transaction.category}`,
        20,
        95
    );

    doc.text(
        `Sender : ${transaction.senderEmail}`,
        20,
        105
    );

    doc.text(
        `Receiver : ${transaction.receiverEmail}`,
        20,
        115
    );

    doc.text(
        `Date : ${new Date(
            transaction.timestamp
        ).toLocaleString()}`,
        20,
        125
    );

    doc.line(20, 135, 190, 135);

    doc.setFontSize(10);

    doc.text(
        "Generated by NeuroWallet",
        20,
        145
    );

    doc.save(
        `Receipt-${transaction.transactionId}.pdf`
    );

};
const copyTransactionId = async () => {

    try {

        await navigator.clipboard.writeText(
            `TXN-${transaction.transactionId}`
        );

        toast.success("Transaction ID copied successfully!");

    } catch {

        toast.error("Failed to copy Transaction ID.");

    }

};
const shareTransaction = async () => {

    const message = `
NeuroWallet Transaction

Reference : TXN-${transaction.transactionId}

Amount : ₹${Number(transaction.amount).toLocaleString()}

Status : ${transaction.status}

Type : ${transaction.type}

Category : ${transaction.category}

Sender : ${transaction.senderEmail}

Receiver : ${transaction.receiverEmail}
`;

    if (navigator.share) {

        try {

            await navigator.share({

                title: "NeuroWallet Transaction",

                text: message

            });

        } catch {

            toast.info("Sharing cancelled.");

        }

    } else {

        await navigator.clipboard.writeText(message);

        toast.success(
            "Transaction copied. You can now paste it anywhere."
        );

    }

};
const printReceipt = () => {

  const printWindow = window.open(
    "",
    "_blank",
    "width=700,height=800"
  );

  printWindow.document.write(`
    <html>
      <head>
        <title>NeuroWallet Receipt</title>

        <style>

          body{
            font-family:Arial;
            padding:40px;
          }

          h1{
            text-align:center;
          }

          table{
            width:100%;
            border-collapse:collapse;
            margin-top:30px;
          }

          td{
            padding:12px;
            border-bottom:1px solid #ddd;
          }

        </style>

      </head>

      <body>

        <h1>NeuroWallet</h1>

        <h3>Transaction Receipt</h3>

        <table>

          <tr>
            <td>Reference</td>
            <td>TXN-${transaction.transactionId}</td>
          </tr>

          <tr>
            <td>Amount</td>
            <td>₹${Number(transaction.amount).toLocaleString()}</td>
          </tr>

          <tr>
            <td>Status</td>
            <td>${transaction.status}</td>
          </tr>

          <tr>
            <td>Type</td>
            <td>${transaction.type}</td>
          </tr>

          <tr>
            <td>Category</td>
            <td>${transaction.category}</td>
          </tr>

          <tr>
            <td>Sender</td>
            <td>${transaction.senderEmail}</td>
          </tr>

          <tr>
            <td>Receiver</td>
            <td>${transaction.receiverEmail}</td>
          </tr>

          <tr>
            <td>Date</td>
            <td>${new Date(transaction.timestamp).toLocaleString()}</td>
          </tr>

        </table>

      </body>

    </html>
  `);

  printWindow.document.close();

  printWindow.focus();

  printWindow.print();

};
  return (

    <div
      className="drawer-overlay"
      onClick={onClose}
    >

      <div
        className="transaction-drawer"
        onClick={(e) =>
          e.stopPropagation()
        }
      >

        <div className="drawer-header">

          <h2>
            Transaction Details
          </h2>

          <button
            className="close-btn"
            onClick={onClose}
          >
            ✕
          </button>

        </div>

        <div className="drawer-body">

          <h1 className="amount">

            ₹
            {Number(
              transaction.amount || 0
            ).toLocaleString()}

          </h1>

          <span
            className={`status ${transaction.status?.toLowerCase()}`}
          >
            {transaction.status}
          </span>

          <div className="detail-row">

            <span>Type</span>

            <strong>
              {transaction.type}
            </strong>

          </div>

          <div className="detail-row">

            <span>Category</span>

            <strong>
              {transaction.category}
            </strong>

          </div>

          <div className="detail-row">

            <span>Sender</span>

            <strong>
              {transaction.senderEmail}
            </strong>

          </div>

          <div className="detail-row">

            <span>Receiver</span>

            <strong>
              {transaction.receiverEmail}
            </strong>

          </div>

          <div className="detail-row">

            <span>Transaction ID</span>

            <strong>
              {transaction.transactionId}
            </strong>

          </div>

          <div className="detail-row">

            <span>Reference</span>

            <strong>

              TXN-

              {transaction.transactionId}

            </strong>

          </div>

          <div className="detail-row">

            <span>Date</span>

            <strong>
              {formatDate(
                transaction.timestamp
              )}
            </strong>

          </div>

          <div className="detail-row">

            <span>Time</span>

            <strong>
              {formatTime(
                transaction.timestamp
              )}
            </strong>

          </div>
<div className="drawer-actions">

   <button
    className="drawer-btn primary"
    onClick={downloadReceipt}
>
    Download Receipt
</button>

   <button
    className="drawer-btn secondary"
    onClick={copyTransactionId}
>
    Copy Transaction ID
</button>

   <button
    className="drawer-btn secondary"
    onClick={shareTransaction}
>
    Share Transaction
</button>
<button
    className="drawer-btn secondary"
    onClick={printReceipt}
>
    Print Receipt
</button>
</div>
        </div>

      </div>

    </div>

  );

}

export default TransactionDetailsDrawer;