import "./GoalRecommendation.css";

import {
    FaLightbulb,
    FaBullseye,
    FaCircleCheck,
    FaArrowTrendUp
} from "react-icons/fa6";

function GoalRecommendation({ wallet }) {

    const balance = wallet?.balance || 0;

    const confidence = 96;

    let priority = "Medium";

    if (balance >= 50000) {

        priority = "Low";

    } else if (balance < 10000) {

        priority = "High";

    }

    return (

        <div className="recommend-card">

            {/* ================= HEADER ================= */}

            <div className="recommend-header">

                <h2>

                    <FaLightbulb />

                    Goal Recommendation

                </h2>

                <span className="recommend-live">

                    LIVE

                </span>

            </div>

            {/* ================= CONFIDENCE ================= */}

            <div className="recommend-confidence">

                <div>

                    <span>

                        AI Confidence

                    </span>

                    <h1>

                        {confidence}%

                    </h1>

                </div>

                <div className="recommend-priority">

                    {priority} Priority

                </div>

            </div>

            {/* ================= RECOMMENDATION ================= */}

            <div className="recommend-box">

                <FaBullseye />

                <div>

                    <h4>

                        Smart Saving Goal

                    </h4>

                    <p>

                        Increase your monthly savings by
                        <strong> ₹5,000 </strong>
                        to reach your target sooner and
                        improve your financial stability.

                    </p>

                </div>

            </div>

            {/* ================= IMPACT ================= */}

            <div className="recommend-impact">

                <span>

                    Expected Impact

                </span>

                <strong>

                    <FaArrowTrendUp />

                    High

                </strong>

            </div>

            {/* ================= FOOTER ================= */}

            <div className="recommend-footer">

                <FaCircleCheck />

                <span>

                    Generated by NeuroWallet AI

                </span>

            </div>

        </div>

    );

}

export default GoalRecommendation;