import "./GoalRecommendation.css";

import {
    FaLightbulb,
    FaBullseye,
    FaCircleCheck,
    FaArrowTrendUp
} from "react-icons/fa6";

function GoalRecommendation({
    goalRecommendation,
    loading
}) {

    const formatCurrency = (amount) =>
        new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
            maximumFractionDigits: 0,
        }).format(amount || 0);

    if (loading) {

        return (

            <div className="recommend-card">

                <div className="recommend-header">

                    <h2>

                        <FaLightbulb />

                        Goal Recommendation

                    </h2>

                    <span className="recommend-live">

                        Loading...

                    </span>

                </div>

                <div
                    style={{
                        padding: "40px",
                        textAlign: "center",
                        fontWeight: "600"
                    }}
                >
                    Generating AI Recommendation...
                </div>

            </div>

        );

    }

    const goalName =
        goalRecommendation?.goalName ??
        "Emergency Fund";

    const targetAmount =
        goalRecommendation?.targetAmount ?? 0;

    const currentAmount =
        goalRecommendation?.currentAmount ?? 0;

    const progress =
        goalRecommendation?.progressPercentage ?? 0;

    const recommendation =
        goalRecommendation?.recommendation ??
        "Continue saving regularly.";

    return (

        <div className="recommend-card">

            {/* Header */}

            <div className="recommend-header">

                <h2>

                    <FaLightbulb />

                    Goal Recommendation

                </h2>

                <span className="recommend-live">

                    LIVE AI

                </span>

            </div>

            {/* Progress */}

            <div className="recommend-confidence">

                <div>

                    <span>

                        Goal Progress

                    </span>

                    <h1>

                        {progress}%

                    </h1>

                </div>

                <div className="recommend-priority">

                    Active Goal

                </div>

            </div>

            {/* Goal */}

            <div className="recommend-box">

                <FaBullseye />

                <div>

                    <h4>

                        {goalName}

                    </h4>

                    <p>

                        Target:

                        <strong>

                            {" "}
                            {formatCurrency(targetAmount)}

                        </strong>

                    </p>

                    <p>

                        Current:

                        <strong>

                            {" "}
                            {formatCurrency(currentAmount)}

                        </strong>

                    </p>

                </div>

            </div>

            {/* Recommendation */}

            <div className="recommend-impact">

                <span>

                    AI Recommendation

                </span>

                <strong>

                    <FaArrowTrendUp />

                    {" "}

                    {recommendation}

                </strong>

            </div>

            {/* Footer */}

            <div className="recommend-footer">

                <FaCircleCheck />

                <span>

                    Generated by NeuroWallet AI

                </span>

            </div>

        </div>

    );

}

export default GoalRecommendation;